### ISSUE TITLE
Use possible entity column names for represantation instead of IDs

### ISSUE THREAD

**Issue by geocfu** [pantherify/YALNT#1]
We should be able to have nova resources using a string column (i.e. name, title, slug etc.) if that is unique, in order to represent the resource when being displayed using that string column.

See image 1 for the currently displayed $title in nova resources.

See image 2 for the specific variable inside each nova resource.

Image 1
![image](https://user-images.githubusercontent.com/9702033/109614256-10cba300-7b3b-11eb-96ad-bbcc3918f7c1.png)

Image 2
![image](https://user-images.githubusercontent.com/9702033/109614632-8df71800-7b3b-11eb-8ed5-9a82ee36816c.png)

**Comment by civicwar** [comment]
In the Models file, if you define 

`public $label = 'your-column-name'`

the generation will use that as the resource name and not the default 'id'.
